"""
init.py — ``baton init``: scaffold BATON.md, .baton.toml, and git hooks.

Steps:
1. Guard against double-initialisation (use --force to override).
2. Detect project name from the current directory name.
3. Detect which agent files already exist (to pre-populate .baton.toml).
4. Write BATON.md from the embedded template.
5. Write .baton.toml (unless it already exists).
6. If .git exists, install a non-blocking pre-commit reminder hook and an
   advisory post-commit drift-check hook.

Phase-1 note: the token-limit trigger is MANUAL (``baton end``) plus this
optional pre-commit reminder.  Baton cannot auto-detect another tool's token
state; the hook only prints a reminder message -- it never blocks a commit.
"""
from __future__ import annotations

import datetime
from pathlib import Path

import typer
from rich.console import Console

from ..adapters.registry import detect_enabled
from .hooks import install_post_commit_hook, install_pre_commit_reminder

console = Console()

# ── BATON.md template ─────────────────────────────────────────────────────────
# Embedded as a string for reliable installation (no importlib.resources needed).
# BatonDocument.load() will parse the ```yaml block inside this template.

_BATON_TEMPLATE = """\
# BATON.md — Living Project Onboarding Document

> Maintained by Baton CLI. Human-reviewed before every update.
> **Test:** could a new agent read this file and contribute without breaking anything?
>
> Edit the YAML block below, then run `baton sync` to propagate to all agent files.

```yaml
baton_version: "1.0"
last_updated: "{today}"
last_session_tool: ""

# ── Project Brief ─────────────────────────────────────────────────────────────
# What is this, who is it for, what problem does it solve?
project:
  name: "{project_name}"
  purpose: ""          # one sentence: what problem does this solve
  target_user: ""      # who uses this
  stage: "prototype"   # idea | prototype | mvp | production

# ── Architecture ──────────────────────────────────────────────────────────────
# How the codebase is structured and why.
architecture:
  overview: ""         # 2-3 sentences max
  key_directories: []  # - path: "src/", purpose: "..."
  entry_point: ""      # e.g. "app.py", "src/index.ts"
  data_flow: ""        # brief: how data moves through the system

# ── Stack ─────────────────────────────────────────────────────────────────────
# Not just WHAT we use but WHY and at what version.
# The "why" stops agents switching frameworks.
# "gotchas" stops them breaking things by upgrading.
# Format: - tool: "", version: "", why: "", gotchas: ""
stack: []

# ── Laws ──────────────────────────────────────────────────────────────────────
# Hard constraints that never change. Written as imperative statements.
# Never deleted once added.
# Example: - "Never use TypeScript. This is a Python-only project."
laws: []

# ── Current Sprint ────────────────────────────────────────────────────────────
current_sprint:
  goal: ""
  done: []       # - feature: "", confidence: stable|fragile|untested, notes: ""
  in_progress: [] # - feature: "", owner: "", context: "", blockers: []
  blocked: []    # - feature: "", reason: "", workaround: ""
  next: []       # - feature: "", priority: high|medium|low, dependencies: []

# ── Decisions ─────────────────────────────────────────────────────────────────
# Append-only — never modify or delete existing entries.
# Each needs evidence from a real code change.
# Format: - id: "d001", what: "", why: "", made: "YYYY-MM-DD", made_in: ""
#   Supersession (optional): supersedes: [d000, ...]  reason: "why this replaces them"
#   Drift detection (optional): evidence: {{type: dependency|file|config_key, value: ""}}
decisions: []

# ── Anti-Decisions ────────────────────────────────────────────────────────────
# Things explicitly ruled out. Stops agents re-suggesting rejected approaches.
# Append-only — never delete.
# Format: - id: "a001", rejected: "", why: "", ruled_out: "YYYY-MM-DD"
#   Supersession (optional): supersedes: [a000, ...]  reason: "why this replaces them"
#   Drift detection (optional): pattern: {{type: regex|import|dependency, value: ""}}, severity: warn|block
anti_decisions: []

# ── Landmines ─────────────────────────────────────────────────────────────────
# Code that LOOKS wrong but is intentional.
# Stops agents "fixing" things that are correct as-is.
# Format: - id: "l001", location: "", looks_like: "", actually: ""
#   Supersession (optional): supersedes: [l000, ...]  reason: "why this replaces them"
#   Drift detection (optional): marker: "", status: open|touched|possibly_resolved
landmines: []

# ── Open Questions ────────────────────────────────────────────────────────────
# Status: open | discussed | resolved
# Agents must NEVER make unilateral decisions on open questions.
open_questions: []

# ── Session Log ───────────────────────────────────────────────────────────────
# Auto-generated by `baton end` (Increment 2). Human-reviewed before appending.
sessions: []
```

---

*Run `baton sync` to push context to all agent config files.*
*Run `baton score` to check document completeness.*
*Run `baton status` to see which files are up to date.*
"""

# ── .baton.toml template ──────────────────────────────────────────────────────

_BATON_TOML_TEMPLATE = """\
# .baton.toml -- Baton project configuration
# https://github.com/AriS10223/baton

[baton]
# LLM provider for `baton end`.  Supported: anthropic | openai | vertex
# Anthropic (default): set ANTHROPIC_API_KEY.  No extra install needed.
# OpenAI:              set OPENAI_API_KEY.      pip install "baton-cli[openai]"
# Vertex AI (Gemini):  set GOOGLE_APPLICATION_CREDENTIALS + BATON_VERTEX_PROJECT.
#                                               pip install "baton-cli[vertex]"
llm_provider = "anthropic"

# Model to use.  Leave empty to use each provider's built-in default:
#   anthropic -> claude-sonnet-4-6
#   openai    -> gpt-4o
#   vertex    -> gemini-1.5-pro
# model = ""

min_diff_lines = 10              # minimum changed lines before triggering a summary
auto_sync = true                 # run `baton sync` automatically after `baton end`

[adapters]
enabled = {adapters}             # which agent files to maintain
"""


def run_init(repo_root: Path, force: bool = False) -> None:
    """Scaffold BATON.md, .baton.toml, and optional git hooks."""
    baton_path = repo_root / "BATON.md"
    toml_path = repo_root / ".baton.toml"

    # ── Guard ─────────────────────────────────────────────────────
    if baton_path.exists() and not force:
        console.print(
            "[yellow]BATON.md already exists.[/yellow] "
            "Use [bold]--force[/bold] to reinitialise."
        )
        raise typer.Exit(0)

    # ── Project name ──────────────────────────────────────────────
    project_name = repo_root.name

    # ── Detect existing agent files ───────────────────────────────
    detected = detect_enabled(repo_root)
    # TOML arrays use double-quoted strings.
    adapter_list = "[" + ", ".join(f'"{a}"' for a in detected) + "]"

    # ── Write BATON.md ────────────────────────────────────────────
    today = datetime.date.today().isoformat()
    baton_content = _BATON_TEMPLATE.format(today=today, project_name=project_name)
    baton_path.write_text(baton_content, encoding="utf-8")
    console.print(f"[green]+[/green] Created [bold]BATON.md[/bold]")

    # ── Write .baton.toml ─────────────────────────────────────────
    if not toml_path.exists():
        toml_content = _BATON_TOML_TEMPLATE.format(adapters=adapter_list)
        toml_path.write_text(toml_content, encoding="utf-8")
        console.print(f"[green]+[/green] Created [bold].baton.toml[/bold]")
    else:
        console.print("[dim]  .baton.toml already exists - skipped[/dim]")

    # ── Git hooks ─────────────────────────────────────────────────────────────
    git_dir = repo_root / ".git"
    if git_dir.is_dir():
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir(exist_ok=True)

        # Pre-commit: reminder to run baton end (non-blocking)
        result = install_pre_commit_reminder(hooks_dir)
        if result == "created":
            console.print("[green]+[/green] Installed pre-commit reminder hook")
        elif result == "updated":
            console.print("[green]+[/green] Updated pre-commit reminder hook")
        else:
            console.print("[dim]  pre-commit hook already up to date[/dim]")

        # Post-commit: advisory drift check (never blocks)
        result = install_post_commit_hook(hooks_dir)
        if result == "created":
            console.print("[green]+[/green] Installed post-commit drift check hook")
        elif result == "updated":
            console.print("[green]+[/green] Updated post-commit drift check hook")
        else:
            console.print("[dim]  post-commit hook already up to date[/dim]")
    else:
        console.print(
            "[dim]  No .git directory found - skipped git hooks.[/dim]"
        )
        console.print(
            "[dim]  Run git init then baton init again to install hooks.[/dim]"
        )

    # ── Next steps ────────────────────────────────────────────────
    console.print()
    console.print("[bold green]Baton initialised! Next steps:[/bold green]")
    console.print("  1. Fill in [bold]BATON.md[/bold] - project name, purpose, stack, laws")
    console.print("  2. Run [bold cyan]baton sync[/bold cyan] to push context to all agent files")
    console.print("  3. Run [bold cyan]baton score[/bold cyan] to check document completeness")
    console.print("  4. At the end of each session: [bold cyan]baton end[/bold cyan] (requires LLM API key)")
