"""
init.py — ``baton init``: scaffold BATON.md, .baton.toml, and a git hook.

Steps:
1. Guard against double-initialisation (use --force to override).
2. Detect project name from the current directory name.
3. Detect which agent files already exist (to pre-populate .baton.toml).
4. Write BATON.md from the embedded template.
5. Write .baton.toml (unless it already exists).
6. If .git exists, install a non-blocking pre-commit reminder hook.

Phase-1 note: the token-limit trigger is MANUAL (``baton end``) plus this
optional pre-commit reminder.  Baton cannot auto-detect another tool's token
state; the hook only prints a reminder message — it never blocks a commit.
"""
from __future__ import annotations

import datetime
import stat
from pathlib import Path

import typer
from rich.console import Console

from ..adapters.registry import detect_enabled

console = Console()

# ── BATON.md template ─────────────────────────────────────────────────────────
# Embedded as a string for reliable installation (no importlib.resources needed).
# BatonDocument.load() will parse the ```yaml block inside this template.

_BATON_TEMPLATE = """\
# BATON.md — Living Project Onboarding Document

> Maintained by Baton CLI. Human-reviewed before every update.
> **Test:** could a new agent read this file and contribute without breaking anything?
>
> Edit the YAML block below, then run `baton sync` to propagate to all agent files.

```yaml
baton_version: "1.0"
last_updated: "{today}"
last_session_tool: ""

# ── Project Brief ─────────────────────────────────────────────────────────────
# What is this, who is it for, what problem does it solve?
project:
  name: "{project_name}"
  purpose: ""          # one sentence: what problem does this solve
  target_user: ""      # who uses this
  stage: "prototype"   # idea | prototype | mvp | production

# ── Architecture ──────────────────────────────────────────────────────────────
# How the codebase is structured and why.
architecture:
  overview: ""         # 2-3 sentences max
  key_directories: []  # - path: "src/", purpose: "..."
  entry_point: ""      # e.g. "app.py", "src/index.ts"
  data_flow: ""        # brief: how data moves through the system

# ── Stack ─────────────────────────────────────────────────────────────────────
# Not just WHAT we use but WHY and at what version.
# The "why" stops agents switching frameworks.
# "gotchas" stops them breaking things by upgrading.
# Format: - tool: "", version: "", why: "", gotchas: ""
stack: []

# ── Laws ──────────────────────────────────────────────────────────────────────
# Hard constraints that never change. Written as imperative statements.
# Never deleted once added.
# Example: - "Never use TypeScript. This is a Python-only project."
laws: []

# ── Current Sprint ────────────────────────────────────────────────────────────
current_sprint:
  goal: ""
  done: []       # - feature: "", confidence: stable|fragile|untested, notes: ""
  in_progress: [] # - feature: "", owner: "", context: "", blockers: []
  blocked: []    # - feature: "", reason: "", workaround: ""
  next: []       # - feature: "", priority: high|medium|low, dependencies: []

# ── Decisions ─────────────────────────────────────────────────────────────────
# Append-only — never modify or delete existing entries.
# Each needs evidence from a real code change.
# Format: - id: "d001", what: "", why: "", made: "YYYY-MM-DD", made_in: ""
decisions: []

# ── Anti-Decisions ────────────────────────────────────────────────────────────
# Things explicitly ruled out. Stops agents re-suggesting rejected approaches.
# Append-only — never delete.
# Format: - id: "a001", rejected: "", why: "", ruled_out: "YYYY-MM-DD"
anti_decisions: []

# ── Landmines ─────────────────────────────────────────────────────────────────
# Code that LOOKS wrong but is intentional.
# Stops agents "fixing" things that are correct as-is.
# Format: - location: "", looks_like: "", actually: ""
landmines: []

# ── Open Questions ────────────────────────────────────────────────────────────
# Status: open | discussed | resolved
# Agents must NEVER make unilateral decisions on open questions.
open_questions: []

# ── Session Log ───────────────────────────────────────────────────────────────
# Auto-generated by `baton end` (Increment 2). Human-reviewed before appending.
sessions: []
```

---

*Run `baton sync` to push context to all agent config files.*
*Run `baton score` to check document completeness.*
*Run `baton status` to see which files are up to date.*
"""

# ── .baton.toml template ──────────────────────────────────────────────────────

_BATON_TOML_TEMPLATE = """\
# .baton.toml — Baton project configuration
# https://github.com/AriS10223/baton

[baton]
# llm_provider = "anthropic"    # anthropic | openai | vertex  (used by `baton end`)
# model = "claude-sonnet-4-6"
min_diff_lines = 10              # minimum changed lines before triggering a summary
auto_sync = true                 # run `baton sync` automatically after `baton end`

[adapters]
enabled = {adapters}             # which agent files to maintain
"""

# ── Pre-commit hook ───────────────────────────────────────────────────────────
# Non-blocking (exits 0). Just prints a reminder to run `baton end`.

_PRE_COMMIT_HOOK = """\
#!/bin/sh
# Baton reminder hook — installed by `baton init`
# This hook never blocks a commit (exits 0).
printf "\\n"
printf "  ╔══════════════════════════════════════════════════════╗\\n"
printf "  ║  Baton: switching AI tools soon?                     ║\\n"
printf "  ║  Run \\'baton end\\' first to capture session context.  ║\\n"
printf "  ╚══════════════════════════════════════════════════════╝\\n"
printf "\\n"
exit 0
"""


def run_init(repo_root: Path, force: bool = False) -> None:
    """Scaffold BATON.md, .baton.toml, and an optional pre-commit hook."""
    baton_path = repo_root / "BATON.md"
    toml_path = repo_root / ".baton.toml"

    # ── Guard ─────────────────────────────────────────────────────
    if baton_path.exists() and not force:
        console.print(
            "[yellow]BATON.md already exists.[/yellow] "
            "Use [bold]--force[/bold] to reinitialise."
        )
        raise typer.Exit(0)

    # ── Project name ──────────────────────────────────────────────
    project_name = repo_root.name

    # ── Detect existing agent files ───────────────────────────────
    detected = detect_enabled(repo_root)
    # TOML arrays use double-quoted strings.
    adapter_list = "[" + ", ".join(f'"{a}"' for a in detected) + "]"

    # ── Write BATON.md ────────────────────────────────────────────
    today = datetime.date.today().isoformat()
    baton_content = _BATON_TEMPLATE.format(today=today, project_name=project_name)
    baton_path.write_text(baton_content, encoding="utf-8")
    console.print(f"[green]+[/green] Created [bold]BATON.md[/bold]")

    # ── Write .baton.toml ─────────────────────────────────────────
    if not toml_path.exists():
        toml_content = _BATON_TOML_TEMPLATE.format(adapters=adapter_list)
        toml_path.write_text(toml_content, encoding="utf-8")
        console.print(f"[green]+[/green] Created [bold].baton.toml[/bold]")
    else:
        console.print("[dim]  .baton.toml already exists - skipped[/dim]")

    # ── Git pre-commit hook ───────────────────────────────────────
    git_dir = repo_root / ".git"
    if git_dir.is_dir():
        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir(exist_ok=True)
        hook_path = hooks_dir / "pre-commit"

        if hook_path.exists():
            console.print("[dim]  pre-commit hook already exists - skipped[/dim]")
        else:
            hook_path.write_text(_PRE_COMMIT_HOOK, encoding="utf-8")
            # Mark executable (owner + group + others).
            mode = hook_path.stat().st_mode
            hook_path.chmod(mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
            console.print("[green]+[/green] Installed pre-commit reminder hook")
    else:
        console.print(
            "[dim]  No .git directory found - skipped pre-commit hook.[/dim]"
        )
        console.print(
            "[dim]  Run [bold]git init[/bold] then [bold]baton init[/bold] "
            "again to install the hook.[/dim]"
        )

    # ── Next steps ────────────────────────────────────────────────
    console.print()
    console.print("[bold green]Baton initialised! Next steps:[/bold green]")
    console.print("  1. Fill in [bold]BATON.md[/bold] - project name, purpose, stack, laws")
    console.print("  2. Run [bold cyan]baton sync[/bold cyan] to push context to all agent files")
    console.print("  3. Run [bold cyan]baton score[/bold cyan] to check document completeness")
