"""cursor.py — Adapter for .cursor/rules/baton.mdc (Cursor IDE).

Cursor rules files use MDC format: a YAML front-matter block followed by
Markdown content.  The front-matter must be at the very top of the file, so
this adapter overrides ``prepare_file`` to handle it correctly:

    ---
    description: Baton project context (auto-generated)
    globs:
    alwaysApply: true
    ---
    <!-- BATON:START — auto-generated, do not edit by hand -->
    ... content ...
    <!-- BATON:END -->
"""
from __future__ import annotations

import re

from .base import BaseAdapter, render_markdown_context, upsert_managed_block

# MDC front-matter prepended to a fresh baton.mdc file.
_MDC_FRONTMATTER = """\
---
description: Baton project context (auto-generated by baton sync)
globs:
alwaysApply: true
---
"""

# Matches an MDC front-matter block at the start of the file.
_FRONTMATTER_RE = re.compile(r"^---\n.*?---\n?", re.DOTALL)


class CursorAdapter(BaseAdapter):
    """Renders BATON.md into .cursor/rules/baton.mdc for Cursor sessions."""

    def render(self, data: dict) -> str:
        return render_markdown_context(data, tool_name="cursor")

    def file_path(self) -> str:
        return ".cursor/rules/baton.mdc"

    def prepare_file(self, existing_content: str, rendered_inner: str) -> str:
        """Preserve or prepend MDC front-matter, then upsert the managed block."""
        if not existing_content.strip():
            # Brand-new file: prepend front-matter then the managed block.
            return _MDC_FRONTMATTER + "\n" + upsert_managed_block("", rendered_inner)

        m = _FRONTMATTER_RE.match(existing_content)
        if m:
            # Existing front-matter found: preserve it, upsert the rest.
            frontmatter = existing_content[: m.end()]
            rest = existing_content[m.end():]
            return frontmatter + "\n" + upsert_managed_block(rest.lstrip("\n"), rendered_inner)

        # No front-matter present: prepend ours, then upsert.
        return _MDC_FRONTMATTER + "\n" + upsert_managed_block(existing_content, rendered_inner)
